services:
  laa-shared-database:
      image: postgres:14.3-alpine
      healthcheck:
        interval: 10s
        timeout: 10s
        retries: 10
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_USERNAME}
        - POSTGRES_USER=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB_NAME}
        - POSTGRES_HOST_AUTH_METHOD= trust
      ports:
        - "5432:5432"
