apiVersion: apps/v1
kind: Deployment
metadata:
  name: laa-record-link-service 
  labels:
    app: laa-record-link-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laa-record-link-service # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: laa-record-link-service  # this should match the selector in service.yml
    spec:
      containers:
        - name: laa-record-link-service
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1200Mi"
              cpu: "300m"
            limits:
              memory: "3000Mi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: SENTRY_ENABLED
              value: "${SENTRY_ENABLED}"
            - name: SENTRY_AUTH_TOKEN
              value: "${SENTRY_AUTH_TOKEN}"
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_password
            - name: POSTGRES_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_name
            - name: POSTGRES_DB_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: rds_instance_address
            - name: POSTGRES_DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: rds_instance_endpoint
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: laa-record-link-service-azure-client-id-k8s
                  key: AZURE_CLIENT_ID
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: laa-record-link-service-azure-client-secret-k8s
                  key: AZURE_CLIENT_SECRET
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: laa-record-link-service-azure-tenant-secret-k8s
                  key: AZURE_TENANT_ID
            - name: BASE_URL_HOMEPAGE
              valueFrom:
                secretKeyRef:
                  name: laa-record-link-service-base-url-k8s
                  key: BASE_URL_HOMEPAGE
