name: Snyk Security Scan

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, closed]
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
      SNYK_ORG_ID:
        required: true
      SNYK_SLACK_WEBHOOK_URL:
        required: false

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Build Docker image
        run: docker build . --file Dockerfile-WorkFlow --tag laa-record-link-service:latest --no-cache

      - name: Run Snyk Docker Scan (CLI)
        continue-on-error: true
        run: |
          snyk test --docker laa-record-link-service:latest \
            --org=${{ secrets.SNYK_ORG_ID }} \
            --sarif \
            --sarif-file-output=snyk_docker_test.sarif \
            --exit-code=0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Debug SARIF file creation
        run: |
          echo "==> Listing files in workspace"
          ls -lah
          echo "==> Checking if snyk_docker_test.sarif exists"
          if [ -f snyk_docker_test.sarif ]; then
            echo "SARIF file created."
          else
            echo "SARIF file NOT created."
          fi

      - name: Replace Security-Severity NULL
        run: |
          if [ -f snyk_docker_test.sarif ]; then
            sed -i 's/"null"/"0"/g' s
