name: Tests

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Run Coverage
        run: |
          ./gradlew test
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 85
          min-coverage-changed-files: 85
          title: Code Coverage
          update-comment: true

      - name: Fail PR if overall coverage is less than 85%
        if: ${{ steps.jacoco.outputs.coverage-overall < 85 }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Overall unit test coverage is less than 85%!')    

      - name: Run IntegrationTest
        run: |
          ./gradlew integrationTest